# Generated by Django 4.2.9 on 2026-02-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_custom_cake_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chemin du ticket JPG'),
        ),
    ]
