# Generated by Django 4.2.9 on 2026-02-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_ticket_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notes administratives'),
        ),
        migrations.AlterField(
            model_name='customcakerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examinée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
