# Generated by Django 4.2.9 on 2026-02-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_adminprofile_order_deleted_at_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimée'),
        ),
    ]
