# Generated by Django 4.2.9 on 2026-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customcakerequest_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MonGâteau', max_length=200)),
                ('store_phone', models.CharField(default='+241 07 40 13 02', max_length=50)),
                ('store_email', models.EmailField(default='mpigajesse23@gmail.com', max_length=254)),
                ('store_address', models.TextField(default='Libreville, Gabon')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('min_order_days', models.PositiveIntegerField(default=2)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('default_currency', models.CharField(default='FCFA', max_length=20)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres administrateur',
                'verbose_name_plural': 'Paramètres administrateur',
            },
        ),
    ]
