# Generated by Django 4.2.9 on 2026-02-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du gâteau')),
                ('cake_type', models.CharField(choices=[('birthday', "🎂 Gâteau d'anniversaire"), ('event', '🎉 Gâteau pour événements'), ('surprise', '🎁 Gâteau surprise'), ('custom', '✨ Gâteau personnalisé'), ('wedding', '💍 Gâteau de mariage')], max_length=20, unique=True, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix indicatif', max_digits=10, verbose_name='Prix de base (FCFA)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Type de gâteau',
                'verbose_name_plural': 'Types de gâteaux',
                'ordering': ['cake_type'],
            },
        ),
    ]
