# Generated by Django 4.2.9 on 2026-02-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caketype',
            name='cake_type',
            field=models.CharField(choices=[('birthday', "🎂 Gâteau d'anniversaire"), ('event', '🎉 Gâteau pour événements'), ('surprise', '🎁 Gâteau surprise'), ('custom', '✨ Gâteau personnalisé'), ('wedding', '💍 Gâteau de mariage')], max_length=20, verbose_name='Type'),
        ),
    ]
