# Generated by Django 4.2.9 on 2026-02-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_caketype_cake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caketype',
            name='image_url',
            field=models.CharField(blank=True, help_text="URL complète de l'image (ex: http://localhost:8000/media/cakes/image.jpg)", max_length=500, null=True, verbose_name="URL de l'image"),
        ),
    ]
